Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit d151aa4a0fa26a795466f2171ef9aa29a4e9f131.

A bot is broken