[BOLT] Fix an unused variable warning
This patch fixes:

  bolt/lib/Core/BinaryFunction.cpp:4117:20: error: unused variable
  'FragmentBaseAddress' [-Werror,-Wunused-variable]